default_language_version:
  python: "3.11"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
        exclude: "starlite/storage/base.py"
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        exclude: "tests/openapi/typescript_converter/test_converter"
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        exclude: "_templates"
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: "test_*"
        args: ["-iii", "-ll", "-s=B308,B703"]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        exclude: "test*|examples*|tools"
        additional_dependencies:
          - pydocstyle[toml]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
            "flake8-type-checking",
            "flake8-implicit-str-concat",
            "flake8-noqa",
            "flake8-return",
            "flake8-secure-coding-standard",
            "flake8-encodings",
            "flake8-use-fstring",
            "flake8-use-pathlib",
          ]
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.16.4
    hooks:
      - id: slotscheck
        exclude: "test_*|docs"
  - repo: https://github.com/pycqa/pylint
    rev: "v2.16.2"
    hooks:
      - id: pylint
        exclude: "test*|tools|docs"
        args: ["--unsafe-load-any-extension=y"]
        additional_dependencies:
          [
            click,
            fast-query-parsers,
            fsspec,
            httpx,
            msgspec,
            multidict,
            opentelemetry-instrumentation-asgi,
            piccolo,
            picologging,
            pydantic,
            pydantic_factories,
            pydantic_openapi_schema,
            python-dotenv,
            python-jose,
            pyyaml,
            redis,
            rich,
            sqlalchemy<2.0.0,
            starlette,
            structlog,
            tortoise_orm,
            uvicorn,
            jsbeautifier,
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.1"
    hooks:
      - id: mypy
        exclude: "test_apps|tools|docs"
        additional_dependencies:
          [
            beanie,
            click,
            fast-query-parsers,
            fsspec,
            httpx,
            msgspec,
            multidict,
            opentelemetry-instrumentation-asgi,
            opentelemetry-sdk,
            piccolo,
            picologging,
            pydantic,
            pydantic_factories,
            pydantic_openapi_schema,
            pytest,
            pytest-mock,
            python-dotenv,
            python-jose,
            rich,
            sqlalchemy<2.0.0,
            sqlalchemy2-stubs,
            starlette,
            structlog,
            tortoise-orm,
            types-beautifulsoup4,
            types-freezegun,
            types-pyyaml,
            types-redis,
            uvicorn,
            jsbeautifier,
            fakeredis,
          ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.295
    hooks:
      - id: pyright
        exclude: "tools|piccolo*|examples/plugins/sqlalchemy_plugin*|using_offset_pagination_with_sqlalchemy"
        additional_dependencies:
          [
            beanie,
            beautifulsoup4,
            brotli,
            click,
            cryptography,
            fast-query-parsers,
            freezegun,
            fsspec,
            httpx,
            hypothesis,
            jinja2,
            mako,
            mongomock_motor,
            msgspec,
            multidict,
            opentelemetry-instrumentation-asgi,
            opentelemetry-sdk,
            piccolo,
            picologging,
            pydantic,
            pydantic_factories,
            pydantic_openapi_schema,
            pytest,
            pytest-mock,
            python-dotenv,
            python-jose,
            pyyaml,
            redis,
            rich,
            sqlalchemy<2.0.0,
            sqlalchemy2-stubs,
            starlette,
            structlog,
            uvicorn,
            jsbeautifier,
            fakeredis,
            pytest-lazy-fixture,
          ]
  - repo: local
    hooks:
      - id: sphinx-lint
        name: sphinx-lint
        language: python
        entry: sphinx-lint
        additional_dependencies: [sphinx-lint]
        types: [rst]
